version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - aws s3 sync ./trendnineweb/dist s3:://trendnineweb-1
artifacts:
    files:
        - './dist/*'
        - './dist/**/*'
